// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: compat.proto

package compat_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Seqno         []byte                 `protobuf:"bytes,3,opt,name=seqno" json:"seqno,omitempty"`
	TopicIDs      []string               `protobuf:"bytes,4,rep,name=topicIDs" json:"topicIDs,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	Key           []byte                 `protobuf:"bytes,6,opt,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_compat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_compat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_compat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetSeqno() []byte {
	if x != nil {
		return x.Seqno
	}
	return nil
}

func (x *Message) GetTopicIDs() []string {
	if x != nil {
		return x.TopicIDs
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_compat_proto protoreflect.FileDescriptor

const file_compat_proto_rawDesc = "" +
	"\n" +
	"\fcompat.proto\x12\tcompat.pb\"\x93\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\fR\x05seqno\x12\x1a\n" +
	"\btopicIDs\x18\x04 \x03(\tR\btopicIDs\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x10\n" +
	"\x03key\x18\x06 \x01(\fR\x03keyB5Z3github.com/libp2p/go-libp2p-pubsub/compat;compat_pb"

var (
	file_compat_proto_rawDescOnce sync.Once
	file_compat_proto_rawDescData []byte
)

func file_compat_proto_rawDescGZIP() []byte {
	file_compat_proto_rawDescOnce.Do(func() {
		file_compat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_compat_proto_rawDesc), len(file_compat_proto_rawDesc)))
	})
	return file_compat_proto_rawDescData
}

var file_compat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_compat_proto_goTypes = []any{
	(*Message)(nil), // 0: compat.pb.Message
}
var file_compat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compat_proto_init() }
func file_compat_proto_init() {
	if File_compat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compat_proto_rawDesc), len(file_compat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compat_proto_goTypes,
		DependencyIndexes: file_compat_proto_depIdxs,
		MessageInfos:      file_compat_proto_msgTypes,
	}.Build()
	File_compat_proto = out.File
	file_compat_proto_goTypes = nil
	file_compat_proto_depIdxs = nil
}
